name: CI

on: [pull_request, push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:schema.graphql"
