name: CI

on: [pull_request, push]

jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
    env:
    run: echo "$SLACK_WEBHOOK_URL"

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: kamilkisiela/graphql-inspector@master
        with:
          schema: "main:schema.graphql"
